# -*- coding: utf-8 -*-
"""Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MY3x1NB8Uq5oqy4HIvBa9qRb4FlyciV_
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import concurrent.futures
import math
import multiprocessing

class Graph:
    def __init__(self, n):
        self.nvertices = n
        self.edges = {}
        self.weights = {}
        self.nodes_set = set()

    def get_nodes(self):
        return self.nodes_set

    def add_edge(self, node1, node2, weight):
        self.nodes_set.add(node1)
        self.nodes_set.add(node2)
        self.edges.setdefault(node1, []).append(node2)
        self.edges.setdefault(node2, []).append(node1)
        self.weights[(node1, node2)] = weight
        self.weights[(node2, node1)] = weight

    def neighbors(self, node):
        return self.edges.get(node, [])

    def has_edge(self, node1, node2):
        return node2 in self.edges.get(node1, [])

    def get_weight(self, node1, node2):
        return self.weights.get((node1, node2), float('inf'))

def generate_random_integer_coordinate(min_val=0, max_val=15, step=1):
    return np.random.choice(np.arange(min_val, max_val + 1, step))

def generate_grid_and_roads():
    road_step_x = generate_random_integer_coordinate(min_val=2, max_val=4)
    road_step_y = generate_random_integer_coordinate(min_val=2, max_val=4)

    min_grid_size = 70
    max_grid_size = 70
    grid_x = generate_random_integer_coordinate(min_val=min_grid_size, max_val=max_grid_size, step=road_step_x)
    grid_y = generate_random_integer_coordinate(min_val=min_grid_size, max_val=max_grid_size, step=road_step_y)

    road_x = [i for i in range(0, grid_x, road_step_x)]
    road_y = [i for i in range(0, grid_y, road_step_y)]

    return (grid_x, grid_y), road_x, road_y, road_step_x, road_step_y

def distance(x1, y1, x2, y2):
    return np.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

def select_unique_point(nodes, exclude_points):
    exclude_set = set(exclude_points)
    point = tuple(map(int, nodes[np.random.randint(len(nodes))]))
    while point in exclude_set:
        point = tuple(map(int, nodes[np.random.randint(len(nodes))]))
    return point

def assign_targets_based_on_distance(start1, start2, start3, target1, target2, target3):
    def total_distance(assignments):
        return sum(distance(start[0], start[1], target[0], target[1])
                  for start, target in assignments)

    from itertools import permutations
    starts = [start1, start2, start3]
    targets = [target1, target2, target3]

    best_assignment = None
    min_distance = float('inf')

    for perm in permutations(targets):
        assignments = zip(starts, perm)
        dist = total_distance(assignments)
        if dist < min_distance:
            min_distance = dist
            best_assignment = perm

    return best_assignment

def check_path_convergence(current_path, best_paths_history, required_stable_iterations=20):

    if len(best_paths_history) < required_stable_iterations:
        return False

    # Get the last n paths where n is required_stable_iterations
    recent_paths = best_paths_history[-required_stable_iterations:]

    # Check if all recent paths are identical to the current path
    return all(path == current_path for path in recent_paths)

def velocity_based_collision_avoidance(best_paths, max_velocity=1.0, min_velocity=0.2, k=0.5, alpha=0.3, epsilon=1e-6):
    if not best_paths or not all(best_paths):
        return best_paths, None

    adjusted_paths = [list(best_paths[0])]
    occupied_spaces = {}
    velocity_profiles = [[] for _ in best_paths]  # Track velocities for each robot

    # First robot moves at constant max velocity
    velocity_profiles[0] = [max_velocity] * len(best_paths[0])

    for robot_id in range(1, len(best_paths)):
        current_path = best_paths[robot_id]
        if not current_path:
            adjusted_paths.append(None)
            continue

        adjusted_path = []
        current_velocities = []
        current_time = 0
        position_index = 0
        current_velocity = max_velocity

        adjusted_path.append(current_path[0])
        current_velocities.append(current_velocity)
        current_pos = current_path[0]

        while position_index < len(current_path) - 1:
            next_index = min(position_index + max(current_velocity, min_velocity), len(current_path) - 1)
            next_pos = current_path[int(next_index)]

            # Count number of conflicts at the next position
            space_time_key = (next_pos[0], next_pos[1], current_time)
            num_conflicts = sum(1 for key in occupied_spaces if key[:2] == space_time_key[:2])

            # Compute adaptive velocity scaling factor
            # Fixed: Check if there are previous velocities before calculating velocity change
            if current_time > 0 and current_velocities:  # Make sure we have previous velocities
                velocity_change = abs(current_velocity - current_velocities[-1])
            else:
                velocity_change = 0

            lambda_j = 1 / (1 + k * num_conflicts + alpha * (velocity_change / (current_velocity + epsilon)))

            # Update velocity based on adaptive scaling
            current_velocity = max(min_velocity, current_velocity * lambda_j)

            if space_time_key not in occupied_spaces:
                adjusted_path.append(next_pos)
                current_velocities.append(current_velocity)
                occupied_spaces[space_time_key] = robot_id
                position_index = int(next_index)
                current_pos = next_pos
            else:
                # If collision detected, slow down more adaptively
                adjusted_path.append(current_pos)
                current_velocities.append(current_velocity)

            current_time += 1

            if len(adjusted_path) > len(current_path) * 3:
                break

        adjusted_paths.append(adjusted_path)
        velocity_profiles[robot_id] = current_velocities

    return adjusted_paths, velocity_profiles


def dynamic_ant_allocation(iteration, total_iterations, base_ants=10, max_ants=30):
    progress = iteration / total_iterations
    ant_scale = 1 / (1 + np.exp(-10 * (progress - 0.5)))
    return int(base_ants + (max_ants - base_ants) * ant_scale)

def batch_update_pheromone(graph, pheromone, all_paths, ev, ph_intensity, extra_impact):
    for edge in pheromone:
        pheromone[edge] *= ev  # Evaporate pheromone

    pheromone_updates = {}

    for path, success in all_paths:
        if not success:
            continue  # Skip unsuccessful paths

        # Reward shorter paths with fewer turns
        path_length = len(path)
        num_turns = 0
        for i in range(1, len(path)-1):
            dx1 = path[i][0] - path[i-1][0]
            dy1 = path[i][1] - path[i-1][1]
            dx2 = path[i+1][0] - path[i][0]
            dy2 = path[i+1][1] - path[i][1]
            if dx1 != dx2 or dy1 != dy2:
                num_turns += 1

        impact = ph_intensity * (extra_impact / (path_length + num_turns))  # Higher impact for shorter paths with fewer turns

        for i in range(path_length - 1):
            edge = tuple(sorted((path[i], path[i + 1])))
            update_value = impact

            if edge in pheromone_updates:
                pheromone_updates[edge] += update_value
            else:
                pheromone_updates[edge] = update_value

    for edge, update in pheromone_updates.items():
        if edge in pheromone:
            pheromone[edge] += update
        else:
            pheromone[edge] = update

    return pheromone

def parallel_aco_path_finding(start_point, target_point, graph, pheromone, alpha, beta, n_ants):
    paths = []

    with multiprocessing.Manager() as manager:
        shared_pheromone = manager.dict(pheromone)

        with concurrent.futures.ThreadPoolExecutor() as executor:
            futures = []
            for _ in range(n_ants):
                future = executor.submit(
                    aco_find_path,
                    start_point,
                    target_point,
                    graph,
                    shared_pheromone,
                    alpha,
                    beta, _, n_ants
                )
                futures.append(future)

            for future in concurrent.futures.as_completed(futures):
                try:
                    path, success = future.result()
                    if success:
                        paths.append(path)
                except Exception as e:
                    print(f"Error in ant path finding: {e}")
                    continue

        final_pheromone = dict(shared_pheromone)
    return paths, final_pheromone

def alpha_find(t, T):
    k = 5
    return 0.5 + (2 - 0.5) * (1 - np.exp(-k * t / T))

def beta_find(t, T):
    k = 5
    return 1 + (3 - 1) * np.exp(-k * t / T)

def calculate_total_cost(path, graph):
    if not path or len(path) < 2:
        return float('inf')

    # Adjust weights to prioritize path length and penalize turns
    w1, w2, w3 = 4, 7, 5  # w3 penalizes turns

    # Calculate path length
    path_length = sum(distance(*path[i], *path[i+1]) for i in range(len(path)-1))

    # Calculate sum of weights along path
    total_weight = sum(graph.get_weight(path[i], path[i+1]) for i in range(len(path)-1))

    # Calculate number of turns
    num_turns = 0
    for i in range(1, len(path)-1):
        dx1 = path[i][0] - path[i-1][0]
        dy1 = path[i][1] - path[i-1][1]
        dx2 = path[i+1][0] - path[i][0]
        dy2 = path[i+1][1] - path[i][1]
        if dx1 != dx2 or dy1 != dy2:
            num_turns += 1

    # Normalize the values
    max_possible_length = distance(0, 0, graph.nvertices, graph.nvertices)
    normalized_length = path_length / max_possible_length
    normalized_weight = total_weight / (graph.nvertices * 5)  # 5 is max_weight
    normalized_turns = num_turns / len(path)  # Normalize by path length

    return w1 * normalized_weight + w2 * normalized_length + w3 * normalized_turns

def aco_find_path(start, end, graph, pheromone, alpha, beta, itr, total_ants):
    path = [start]
    current = start
    visited = {start}

    while current != end:
        neighbors = [n for n in graph.neighbors(current) if n not in visited]

        if not neighbors:
            return path, False

        if end in neighbors:
            path.append(end)
            return path, True

        probs = []
        total_prob = 0

        for neighbor in neighbors:
            ph = pheromone.get(tuple(sorted((current, neighbor))), 0.1)
            # Modified to use total_cost instead of just distance
            total_cost = calculate_total_cost([current, neighbor], graph)
            if itr > total_ants/25:
                heuristic = 1.0 / (total_cost + 1e-6)
            else:
                x1, y1 = neighbor
                x2, y2 = end
                heuristic = 1/ distance(x1,y1, x2,y2)
            prob = np.exp((np.log(ph + 1e-6) * alpha) + (np.log(heuristic + 1e-6) * beta))
            probs.append((neighbor, prob))
            total_prob += prob

        if total_prob == 0:
            next_node = neighbors[np.random.randint(len(neighbors))]
        else:
            normalized_probs = [p / total_prob for _, p in probs]
            neighbor_list = [n for n, _ in probs]

            try:
                if itr > total_ants/10:
                    next_node = neighbor_list[np.random.choice(len(neighbor_list), p=normalized_probs)]
                else:
                    next_node = max(probs, key=lambda x: x[1])[0]
            except ValueError:
                next_node = neighbors[np.random.randint(len(neighbors))]

        path.append(next_node)
        visited.add(next_node)
        current = next_node

        if len(path) > 50:
            return path, False

    return path, True

def calculate_work(path, velocities, mass=1.0):

    if not path or len(path) < 2 or not velocities:
        return 0.0

    total_work = 0.0

    for i in range(len(path)-1):
        # Get current segment details
        distance_segment = distance(*path[i], *path[i+1])
        v_initial = velocities[i]
        v_final = velocities[i+1] if i+1 < len(velocities) else velocities[-1]
        avg_velocity = (v_initial + v_final) / 2

        # Calculate work components
        kinetic_work = 0.5 * mass * (v_final**2 - v_initial**2)
        motion_work = mass * avg_velocity * distance_segment
        acceleration_work = mass * abs(v_final - v_initial) * distance_segment

        segment_work = kinetic_work + motion_work + acceleration_work
        total_work += segment_work

    return total_work

# Ensure weight handling when pruning
def prune_edges_with_recovery(graph, start_points, target_points, angle_threshold=30, distance_factor=1.2):
    pruned_graph = Graph(graph.nvertices)
    pruned_edges = {}  # To store pruned edges with weight info
    critical_points = start_points + target_points

    # Copy original graph and retain weights
    for node in graph.get_nodes():
        for neighbor in graph.neighbors(node):
            pruned_graph.add_edge(node, neighbor, graph.get_weight(node, neighbor))

    for node in graph.get_nodes():
        for neighbor in graph.neighbors(node):
            if node in critical_points or neighbor in critical_points:
                continue

            # Check if the edge should be pruned
            should_prune = False
            worst_angle = 0
            worst_distance_ratio = 0

            for start in start_points:
                for target in target_points:
                    direct_vector = np.array(target) - np.array(start)
                    edge_vector = np.array(neighbor) - np.array(node)

                    if np.all(direct_vector == 0) or np.all(edge_vector == 0):
                        continue

                    cos_angle = np.dot(direct_vector, edge_vector) / (
                        np.linalg.norm(direct_vector) * np.linalg.norm(edge_vector))
                    angle = np.degrees(np.arccos(np.clip(cos_angle, -1.0, 1.0)))

                    direct_dist = np.linalg.norm(direct_vector)
                    path_dist = (np.linalg.norm(np.array(node) - np.array(start)) +
                                 np.linalg.norm(np.array(neighbor) - np.array(node)) +
                                 np.linalg.norm(np.array(target) - np.array(neighbor)))

                    distance_ratio = path_dist / direct_dist

                    if angle > angle_threshold and distance_ratio > distance_factor:
                        should_prune = True
                        worst_angle = max(worst_angle, angle)
                        worst_distance_ratio = max(worst_distance_ratio, distance_ratio)
                        break

                if should_prune:
                    break

            if should_prune:
                edge = tuple(sorted([node, neighbor]))
                midpoint = tuple((np.array(node) + np.array(neighbor)) / 2)
                edge_vector = np.array(neighbor) - np.array(node)
                edge_direction = edge_vector / np.linalg.norm(edge_vector)

                prune_info = {
                    'midpoint': midpoint,
                    'angle': worst_angle,
                    'distance_ratio': worst_distance_ratio,
                    'direction': tuple(edge_direction),
                    'weight': graph.get_weight(node, neighbor)  # Store the weight of the pruned edge
                }

                if edge not in pruned_edges:
                    pruned_edges[edge] = prune_info
                    if neighbor in pruned_graph.edges.get(node, []):
                        pruned_graph.edges[node].remove(neighbor)
                    if node in pruned_graph.edges.get(neighbor, []):
                        pruned_graph.edges[neighbor].remove(node)

    return pruned_graph, pruned_edges


# Ensure weight restoration when recovering edges
def recover_critical_edges(graph, pruned_edges, current_paths, local_range=5.0,
                         recovery_threshold=0.5, max_density=3, alignment_weight=0.7):
    if not current_paths or not any(current_paths):
        return graph

    recovered_edges = {}

    path_segments = []
    for path in current_paths:
        if len(path) < 2:
            continue
        for i in range(len(path) - 1):
            segment_start = np.array(path[i])
            segment_end = np.array(path[i + 1])
            segment_vector = segment_end - segment_start
            segment_direction = segment_vector / np.linalg.norm(segment_vector)
            path_segments.append({
                'start': segment_start,
                'end': segment_end,
                'direction': segment_direction,
                'midpoint': (segment_start + segment_end) / 2
            })

    if not path_segments:
        return graph

    path_points = np.array([segment['midpoint'] for segment in path_segments])

    for edge, edge_info in pruned_edges.items():
        node1, node2 = edge
        midpoint = np.array(edge_info['midpoint'])
        edge_direction = np.array(edge_info['direction'])

        distances = np.linalg.norm(path_points - midpoint, axis=1)

        if np.any(distances <= local_range):
            nearby_count = sum(1 for rec_mid, _ in recovered_edges.items()
                             if np.linalg.norm(np.array(rec_mid) - midpoint) <= local_range / 2)

            if nearby_count >= max_density:
                continue

            best_alignment = 0
            for segment in path_segments:
                if np.linalg.norm(segment['midpoint'] - midpoint) <= local_range:
                    alignment = abs(np.dot(segment['direction'], edge_direction))
                    best_alignment = max(best_alignment, alignment)

            base_score = 1.0 / (edge_info['angle'] * edge_info['distance_ratio'])
            alignment_score = best_alignment
            recovery_score = (1 - alignment_weight) * base_score + alignment_weight * alignment_score

            if recovery_score >= recovery_threshold:
                graph.add_edge(node1, node2, edge_info['weight'])  # Restore weight
                recovered_edges[tuple(edge)] = edge_info['midpoint']

    return graph


def run_multi_robot_aco(start_points, target_points, graph, total_ants=100,
                                   similarity_threshold=10, prune_start_iteration=30,
                                   angle_threshold=45, distance_factor=1.5):
    """Modified ACO function with edge pruning after specified iterations"""
    paths_per_robot = [[] for _ in range(len(start_points))]
    best_paths_history = [[] for _ in range(len(start_points))]
    best_lengths = [float('inf') for _ in range(len(start_points))]

    pheromones = [{tuple(sorted((node, neighbor))): 0.1
                   for node in graph.get_nodes()
                   for neighbor in graph.neighbors(node)}
                  for _ in range(len(start_points))]

    convergence_check_start = total_ants // 3
    required_stable_iterations = 20
    convergence_iterations = [None for _ in range(len(start_points))]
    all_converged = False

    # Store original graph for pruning
    current_graph = graph
    pruned_edges = {}
    has_pruned = False

    for iteration in range(total_ants):
        if all_converged:
            print(f"All robots converged. Stopping at iteration {iteration}")
            break

        # Apply pruning if we've reached the specified iteration
        if iteration == prune_start_iteration and not has_pruned:
            print(f"Applying edge pruning at iteration {iteration}")
            current_graph, pruned_edges = prune_edges_with_recovery(
                graph, start_points, target_points,
                angle_threshold, distance_factor
            )
            has_pruned = True

        alpha = alpha_find(iteration, total_ants)
        beta = beta_find(iteration, total_ants)

        for robot_idx, (start, target) in enumerate(zip(start_points, target_points)):
            if convergence_iterations[robot_idx] is not None:
                continue

            try:
                paths, updated_pheromones = parallel_aco_path_finding(
                start, target, current_graph, pheromones[robot_idx],
                alpha, beta, n_ants=1
            )
                pheromones[robot_idx] = updated_pheromones  # Store the updated pheromones

                if not paths and has_pruned:
                    current_graph = recover_critical_edges(
                        current_graph, pruned_edges, paths_per_robot
                    )
                    paths, updated_pheromones = parallel_aco_path_finding(
                        start, target, current_graph, pheromones[robot_idx],
                        alpha, beta, n_ants=1
                    )
                    pheromones[robot_idx] = updated_pheromones  # Store the updated pheromones

                if paths:
                    current_best = min(paths, key=len)
                    current_length = len(current_best)

                    if current_length < best_lengths[robot_idx]:
                        best_lengths[robot_idx] = current_length
                        paths_per_robot[robot_idx] = current_best
                        best_paths_history[robot_idx].append(current_best)
                    else:
                        best_paths_history[robot_idx].append(paths_per_robot[robot_idx])

                    if iteration >= convergence_check_start:
                        if check_path_convergence(
                            paths_per_robot[robot_idx],
                            best_paths_history[robot_idx],
                            required_stable_iterations
                        ):
                            convergence_iterations[robot_idx] = iteration
                            print(f"Robot {robot_idx+1} converged at iteration {iteration}")

                            if all(conv is not None for conv in convergence_iterations):
                                all_converged = True

            except Exception as e:
                print(f"Error in iteration {iteration} for robot {robot_idx}: {e}")
                continue

    return paths_per_robot

# Main Execution
if __name__ == "__main__":
    grid_size, road_x, road_y, road_step_x, road_step_y = generate_grid_and_roads()
    grid_size = tuple(map(int, grid_size))
    print(f"Grid Size: {grid_size}, Road Steps: ({road_step_x}, {road_step_y})")

    G = Graph(len(road_x) * len(road_y))
    min_weight = 1
    max_weight = 5

    for x in road_x:
        for y in road_y:
            if (x + road_step_x, y) in [(rx, ry) for rx in road_x for ry in road_y]:
                # Base weight is the road step, multiplied by a random discomfort factor
                discomfort = np.random.uniform(1.0, 1.5)  # 1.0 to 1.5 represents path conditions
                weight = road_step_x * discomfort
                G.add_edge((x, y), (x + road_step_x, y), weight)
            if (x, y + road_step_y) in [(rx, ry) for rx in road_x for ry in road_y]:
                discomfort = np.random.uniform(1.0, 1.5)
                weight = road_step_y * discomfort
                G.add_edge((x, y), (x, y + road_step_y), weight)

    nodes = [tuple(map(int, node)) for node in G.get_nodes()]
    start_point1 = tuple(map(int, nodes[np.random.randint(len(nodes))]))
    start_point2 = tuple(map(int, nodes[np.random.randint(len(nodes))]))
    start_point3 = tuple(map(int, nodes[np.random.randint(len(nodes))]))
    target_candidates = [select_unique_point(nodes, [start_point1, start_point2, start_point3]) for _ in range(3)]

    t1, t2, t3 = target_candidates
    target_point1, target_point2, target_point3 = assign_targets_based_on_distance(
        start_point1, start_point2, start_point3, t1, t2, t3
    )

    print("Start Point 1:", start_point1)
    print("Start Point 2:", start_point2)
    print("Start Point 3:", start_point3)
    print("Target Point 1:", target_point1)
    print("Target Point 2:", target_point2)
    print("Target Point 3:", target_point3)

    # Get best paths using ACO
    best_paths = run_multi_robot_aco(
    [start_point1, start_point2, start_point3],
    [target_point1, target_point2, target_point3],
    G,
    total_ants=100,

    similarity_threshold=10,
    prune_start_iteration=20,  # Start pruning after 30 iterations
    angle_threshold=45,        # Maximum angle deviation for pruning
    distance_factor=1.5        # Maximum path length ratio for pruning
    )
    ROBOT_MASS = 1.0  # kg
    total_ants =100

    # Apply velocity-based collision avoidance
    collision_free_paths, velocity_profiles = velocity_based_collision_avoidance(best_paths)

    for i, (path, velocities) in enumerate(zip(collision_free_paths, velocity_profiles)):
        print(f'Path {i+1}: ', path)
        if path and velocities:
            total_cost = calculate_total_cost(path, G)
            total_work = calculate_work(path, velocities, ROBOT_MASS)
            print(f"\nRobot {i+1}:")
            print(f"Total Cost: {total_cost:.2f}")
            print(f"Total Work: {total_work:.2f} Joules")

    # Visualization
    fig, ax = plt.subplots(figsize=(8, 8))

    # Draw roads
    for edge in G.get_nodes():
        for neighbor in G.neighbors(edge):
            ax.plot([edge[0], neighbor[0]], [edge[1], neighbor[1]],
                   color='black', linewidth=1, alpha=0.5)

    # Plot start and target points
    ax.scatter(*start_point1, color='green', s=100, label='Start A')
    ax.scatter(*target_point1, color='red', s=100, label='Target A')
    ax.scatter(*start_point2, color='blue', s=100, label='Start B')
    ax.scatter(*target_point2, color='purple', s=100, label='Target B')
    ax.scatter(*start_point3, color='violet', s=100, label='Start C')
    ax.scatter(*target_point3, color='yellow', s=100, label='Target C')

    # Initialize robots and paths
    robot1, = ax.plot([], [], 'go', markersize=10, label='Robot A')
    robot2, = ax.plot([], [], 'bo', markersize=10, label='Robot B')
    robot3, = ax.plot([], [], 'yo', markersize=10, label='Robot C')

    # Add path lines
    path_line1, = ax.plot([], [], 'g-', alpha=0.5)
    path_line2, = ax.plot([], [], 'b-', alpha=0.5)
    path_line3, = ax.plot([], [], 'm-', alpha=0.5)

    def update(frame):
        for robot, path, line in zip([robot1, robot2, robot3],
                                    collision_free_paths,
                                    [path_line1, path_line2, path_line3]):
            if path and frame < len(path):
                current_data = list(zip(*path[:frame + 1]))
                if current_data:
                    robot.set_data(*current_data)
                    line.set_data(*current_data)

        return robot1, robot2, robot3, path_line1, path_line2, path_line3

    # Create animation
    max_frames = max(len(path) if path else 0 for path in collision_free_paths)
    ani = animation.FuncAnimation(
        fig, update,
        frames=max_frames,
        interval=200,
        blit=True
    )

    plt.legend()
    plt.show()